import subprocess
import sys
from pathlib import Path

import pytest

from idl2proto import __version__, main

EXAMPLES = Path(__file__).resolve().parent.parent / "examples"


def convert(tmp_path, idl_text, *args):
    src = tmp_path / "in.idl"
    src.write_text(idl_text, encoding="utf-8")
    out = tmp_path / "in.proto"
    assert main([str(src), "-o", str(out), "-q", *args]) == 0
    return out.read_text(encoding="utf-8")


@pytest.mark.parametrize("name", ["sensors", "common"])
def test_examples_match_golden_files(tmp_path, name):
    assert main([str(EXAMPLES / "sensors.idl"), "-r", "-q",
                 "-o", str(tmp_path / "sensors.proto")]) == 0
    expected = (EXAMPLES / "out" / f"{name}.proto").read_text(encoding="utf-8")
    actual = (tmp_path / f"{name}.proto").read_text(encoding="utf-8")
    assert actual.splitlines()[1:] == expected.splitlines()[1:]
    assert actual.startswith(f"// Generated by idl2proto {__version__} ")


def test_examples_compile_with_protoc(tmp_path):
    protoc = pytest.importorskip("grpc_tools.protoc")
    import grpc_tools

    out_dir = tmp_path / "py"
    out_dir.mkdir()
    std_include = Path(grpc_tools.__file__).parent / "_proto"
    rc = protoc.main(["protoc", f"-I{EXAMPLES / 'out'}", f"-I{std_include}",
                      f"--python_out={out_dir}",
                      str(EXAMPLES / "out" / "sensors.proto"),
                      str(EXAMPLES / "out" / "common.proto")])
    assert rc == 0


def test_syntax_error_exits_1(tmp_path, capsys):
    src = tmp_path / "bad.idl"
    src.write_text("struct A { long x }; \n", encoding="utf-8")
    assert main([str(src), "-o", "-"]) == 1
    assert "bad.idl:1: error:" in capsys.readouterr().err


def test_utf8_bom_is_accepted(tmp_path):
    proto = convert(tmp_path, "\ufeffstruct S { long x; };")
    assert "int32 x = 1;" in proto


def test_nested_sequence_closing_brackets(tmp_path):
    proto = convert(tmp_path, "struct S { sequence<sequence<long, 4>> m; };")
    assert "repeated Int32List m = 1;" in proto


def test_explicit_ids_continue_sequentially(tmp_path):
    proto = convert(tmp_path, "struct S { @id(10) long a; long b; };")
    assert "int32 a = 10;" in proto and "int32 b = 11;" in proto


def test_enum_map_key_becomes_int32(tmp_path):
    proto = convert(tmp_path, "enum E { A, B }; struct S { map<E, string> m; };")
    assert "map<int32, string> m = 1;" in proto


def test_any_imports_well_known_type(tmp_path):
    proto = convert(tmp_path, "struct S { any payload; };")
    assert 'import "google/protobuf/any.proto";' in proto
    assert "google.protobuf.Any payload = 1;" in proto


def test_snake_case_option(tmp_path):
    proto = convert(tmp_path, "struct S { long fooBar; };", "--snake-case")
    assert "int32 foo_bar = 1;" in proto


def test_module_entry_point(tmp_path):
    result = subprocess.run([sys.executable, "-m", "idl2proto", "--version"],
                            capture_output=True, text=True)
    assert result.returncode == 0
    assert __version__ in result.stdout
